name: Run Package

on:
  push:
    branches:
      - "master"
      - "release*"

permissions:
  id-token: write
  contents: read

jobs:
  run-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest commit in the PR
        uses: actions/checkout@v3
      - name: Set up Docker QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - name: Run make docker
        run: |
          make docker
