name: Run Package

on:
  push:
    branches:
      - "master"
      - "release*"

permissions:
  id-token: write
  contents: read

jobs:
  run-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest commit in the PR
        uses: actions/checkout@v3
      - name: Set up Docker QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "eu-west-1"
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Run make docker
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          make docker
          docker push ${REGISTRY}/amazon-k8s-cni:${IMAGE_TAG}
          docker push ${REGISTRY}/amazon-k8s-cni-init:${IMAGE_TAG}
